# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13b2761a53c46270e0f64b7448ec428b5a6068d84c32302d6c4f162de20e451b76f85da12c50d0ceb86e2f772b1add4cbf7ad402b1e5c6d16b3cd372cad9bf72

test:
  secret_key_base: 368e187a7d02a0003076fc8e9fc05816c895907141265544c42f42305ac29d5253fde1e1790e930f22dc979a8f1e8042f75718f84250c19d836d4797c1dd6714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
